apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

def openCVersionName = "4.5.1"
def openCVersionCode = ((4 * 100 + 5) * 100 + 1) * 10 + 0

println "OpenCV: " + openCVersionName + " " + project.buildscript.sourceFile

android {
    compileSdkVersion 33 // Updated to a more recent version
    namespace = "org.opencv"

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 33 // Updated to match compileSdkVersion

        versionCode openCVersionCode
        versionName openCVersionName

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                targets "opencv_jni_shared"
            }
        }
    }

    buildTypes {
        debug {
            packagingOptions {
                doNotStrip '**/*.so'  // Controlled by OpenCV CMake scripts
            }
        }
        release {
            packagingOptions {
                doNotStrip '**/*.so'  // Controlled by OpenCV CMake scripts
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8 // Updated to Java 8
        targetCompatibility JavaVersion.VERSION_1_8 // Updated to Java 8
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['native/libs']
            java.srcDirs = ['java/src']
            aidl.srcDirs = ['java/src']
            res.srcDirs = ['java/res']
            manifest.srcFile 'java/AndroidManifest.xml'
        }
    }

    externalNativeBuild {
        cmake {
            path (project.projectDir.toString() + '/libcxx_helper/CMakeLists.txt')
        }
    }
}


// Get the GitHub token from secrets.properties file
def secretsPropertiesFile = rootProject.file("secrets.properties")
def secrets = new Properties()

// Optional: load from file if needed
// if (secretsPropertiesFile.exists()) {
//     secrets.load(new FileInputStream(secretsPropertiesFile))
//     githubToken = secrets.getProperty("gpr.key")
// }

def githubToken = {
    def propsFile = rootProject.file('secrets.properties')
    def props = new Properties()
    props.load(new FileInputStream(propsFile))
    def token = props.getProperty('GITHUB_TOKEN')
    if (!token) {
        throw new GradleException('GITHUB_TOKEN not found in secrets.properties')
    }
    return token
}()


// Publish the AAR file to the GitHub Package Registry as a Maven package
publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.prayag'
            artifactId = 'opencv'
            version = '0.0.6'


            artifact("$buildDir/outputs/aar/OpenCV-sdk-release.aar")
        }
    }

    repositories {
        maven {
            name = 'omr_package'
            url = uri('https://maven.pkg.github.com/Prayag887/omr_scanner')
            credentials {
                username = 'Prayag887'
                password = githubToken
            }
        }
    }
}

dependencies {
    // Add any required dependencies here

}